# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# github actions 中文文档 https://docs.github.com/cn/actions/getting-started-with-github-actions

name: build

on:
  push:
    branches: [ dev, master ]
    paths:
      - '.github/workflows/*'
      - 'src/**'
      - 'test/**'
      - 'examples/**'
      - 'build/**'
      - 'server/**' # 暂时用不到，先留着吧，后面会加关于 server 的处理

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm test
    - run: npm run build --if-present
