# 测试机安装 git node pm2

name: deploy to tecent server - server

on:
    push:
      branches:
        - 'server'
      paths:
        - '.github/workflows/*'
        - 'server/**'
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: set ssh key # 临时设置 ssh key
          run: |
            mkdir -p ~/.ssh/
            echo "${{secrets.WFP_ID_RSA}}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan ${{secrets.TECENT_SERVER}} >> ~/.ssh/known_hosts
        - name: deploy
          run: |
            ssh work@${{secrets.TECENT_SERVER}} "
                cd /home/work/wangEditor-team/wangEditor; # 事先 git clone ** server 分支**
                git checkout . ; # 清空所有改动
                git checkout server; # 切换到 server 分支
                git pull origin server;
                npm i;
                npm run server; # 启动或重启，保证服务器安装了 pm2
                echo ========= wangEditor server start success =========
            "
        - name: delete ssh key # 删除 ssh key
          run: rm -rf ~/.ssh/id_rsa
