server:
  port: 8081
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bj-cynosdbmysql-grp-46blpvhu.sql.tencentcdb.com:27549/wangxietest2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: AK47m4a1
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  resources:
    chain:
     cache: false
  #若使用jsp则打开以下配置
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
  #若使用html则使用thymeleaf及以下配置
#  thymeleaf:
#    prefix: classpath:/static/html/
#    suffix: .html
#    cache: false #关闭缓存
#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wangxie.wangxieweb.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

