<?php
    header('Content-Type:application/json');
    $array = [
        'code'    => 0,
        'msg'     => '',
        'count'   => 6,
        'data'    => [
            [
                'id'            => 1,
                'username'       => 'juan1',
                'name'           => '汤伟诚',
                'role'           => '部员',
                'sex'            => '男',
                'grade'            => '2018',
                'major'          => '车辆工程',
                'college'        => '车辆与能源学院',
                'student_id'     => '201811130342',
                'department'     => '开发部',
                'QQ'             => '449097632',
                'status'         => '正常',
                'ban_deadline'   => date('Y-m-d H:i:s')],
            [
                'id'            => 1,
                'username'       => 'juan1',
                'name'           => '汤伟诚',
                'role'           => '部员',
                'sex'            => '男',
                'grade'            => '2018',
                'major'          => '车辆工程',
                'college'        => '车辆与能源学院',
                'student_id'     => '201811130342',
                'department'     => '开发部',
                'QQ'             => '449097632',
                'status'         => '正常',
                'ban_deadline'   => date('Y-m-d H:i:s')],
            [
                'id'            => 1,
                'username'       => 'juan1',
                'name'           => '汤伟诚',
                'role'           => '部员',
                'sex'            => '男',
                'grade'            => '2018',
                'major'          => '车辆工程',
                'college'        => '车辆与能源学院',
                'student_id'     => '201811130342',
                'department'     => '开发部',
                'QQ'             => '449097632',
                'status'         => '正常',
                'ban_deadline'   => date('Y-m-d H:i:s')],
            [
                'id'            => 1,
                'username'       => 'juan1',
                'name'           => '汤伟诚',
                'role'           => '部员',
                'sex'            => '男',
                'grade'            => '2018',
                'major'          => '车辆工程',
                'college'        => '车辆与能源学院',
                'student_id'     => '201811130342',
                'department'     => '开发部',
                'QQ'             => '449097632',
                'status'         => '正常',
                'ban_deadline'   => date('Y-m-d H:i:s')],
            [
                'id'            => 1,
                'username'       => 'juan1',
                'name'           => '汤伟诚',
                'role'           => '部员',
                'sex'            => '男',
                'grade'            => '2018',
                'major'          => '车辆工程',
                'college'        => '车辆与能源学院',
                'student_id'     => '201811130342',
                'department'     => '开发部',
                'QQ'             => '449097632',
                'status'         => '正常',
                'ban_deadline'   => date('Y-m-d H:i:s')],
            [
                'id'            => 1,
                'username'       => 'juan1',
                'name'           => '汤伟诚',
                'role'           => '部员',
                'sex'            => '男',
                'grade'            => '2018',
                'major'          => '车辆工程',
                'college'        => '车辆与能源学院',
                'student_id'     => '201811130342',
                'department'     => '开发部',
                'QQ'             => '449097632',
                'status'         => '正常',
                'ban_deadline'   => date('Y-m-d H:i:s')]
        ]
    ];

    echo json_encode($array);

