<?php
    header('Content-Type:application/json');
    $array = [
        'code'    => 0,
        'msg'     => '',
        'count'   => 6,
        'data'    => [
            [
                'id'            => 1,
                'name'       => '汤伟诚',
                'sex'            => '男',
                'student_id'          => '449097632',
                'college'             => '车辆与能源学院',
                'major'             => '车辆工程(卓越计划)',
                'wanted_department1'            => '开发',
                'wanted_department2'      => '运维',
                'adjust'        => '是',
                'answer1'         => '除此之外，小米11新版系统修复了虚拟AB分区异常重启后判断异常导致OTA启动失败的问题；修复了低概率闪屏问题。',
                'answer2'   => '除此之外，小米11新版系统修复了虚拟AB分区异常重启后判断异常导致OTA启动失败的问题；修复了低概率闪屏问题。',
                'answer3'    => '除此之外，小米11新版系统修复了虚拟AB分区异常重启后判断异常导致OTA启动失败的问题；修复了低概率闪屏问题。',
                'update_time'    => date('Y-m-d H:i:s')],
            [
                'id'            => 1,
                'name'       => '汤伟诚',
                'sex'            => '男',
                'student_id'          => '449097632',
                'college'             => '车辆与能源学院',
                'major'             => '车辆工程(卓越计划)',
                'wanted_department1'            => '开发',
                'wanted_department2'      => '运维',
                'adjust'        => '是',
                'answer1'         => '除此之外，小米11新版系统修复了虚拟AB分区异常重启后判断异常导致OTA启动失败的问题；修复了低概率闪屏问题。',
                'answer2'   => '除此之外，小米11新版系统修复了虚拟AB分区异常重启后判断异常导致OTA启动失败的问题；修复了低概率闪屏问题。',
                'answer3'    => '除此之外，小米11新版系统修复了虚拟AB分区异常重启后判断异常导致OTA启动失败的问题；修复了低概率闪屏问题。',
                'update_time'    => date('Y-m-d H:i:s')],
            [
                'id'            => 1,
                'name'       => '汤伟诚',
                'sex'            => '男',
                'student_id'          => '449097632',
                'college'             => '车辆与能源学院',
                'major'             => '车辆工程(卓越计划)',
                'wanted_department1'            => '开发',
                'wanted_department2'      => '运维',
                'adjust'        => '是',
                'answer1'         => '除此之外，小米11新版系统修复了虚拟AB分区异常重启后判断异常导致OTA启动失败的问题；修复了低概率闪屏问题。',
                'answer2'   => '除此之外，小米11新版系统修复了虚拟AB分区异常重启后判断异常导致OTA启动失败的问题；修复了低概率闪屏问题。',
                'answer3'    => '除此之外，小米11新版系统修复了虚拟AB分区异常重启后判断异常导致OTA启动失败的问题；修复了低概率闪屏问题。',
                'update_time'    => date('Y-m-d H:i:s')],
            [
                'id'            => 1,
                'name'       => '汤伟诚',
                'sex'            => '男',
                'student_id'          => '449097632',
                'college'             => '车辆与能源学院',
                'major'             => '车辆工程(卓越计划)',
                'wanted_department1'            => '开发',
                'wanted_department2'      => '运维',
                'adjust'        => '是',
                'answer1'         => '除此之外，小米11新版系统修复了虚拟AB分区异常重启后判断异常导致OTA启动失败的问题；修复了低概率闪屏问题。',
                'answer2'   => '除此之外，小米11新版系统修复了虚拟AB分区异常重启后判断异常导致OTA启动失败的问题；修复了低概率闪屏问题。',
                'answer3'    => '除此之外，小米11新版系统修复了虚拟AB分区异常重启后判断异常导致OTA启动失败的问题；修复了低概率闪屏问题。',
                'update_time'    => date('Y-m-d H:i:s')],
            [
                'id'            => 1,
                'name'       => '汤伟诚',
                'sex'            => '男',
                'student_id'          => '449097632',
                'college'             => '车辆与能源学院',
                'major'             => '车辆工程(卓越计划)',
                'wanted_department1'            => '开发',
                'wanted_department2'      => '运维',
                'adjust'        => '是',
                'answer1'         => '除此之外，小米11新版系统修复了虚拟AB分区异常重启后判断异常导致OTA启动失败的问题；修复了低概率闪屏问题。',
                'answer2'   => '除此之外，小米11新版系统修复了虚拟AB分区异常重启后判断异常导致OTA启动失败的问题；修复了低概率闪屏问题。',
                'answer3'    => '除此之外，小米11新版系统修复了虚拟AB分区异常重启后判断异常导致OTA启动失败的问题；修复了低概率闪屏问题。',
                'update_time'    => date('Y-m-d H:i:s')],
            [
                'id'            => 1,
                'name'       => '汤伟诚',
                'sex'            => '男',
                'student_id'          => '449097632',
                'college'             => '车辆与能源学院',
                'major'             => '车辆工程(卓越计划)',
                'wanted_department1'            => '开发',
                'wanted_department2'      => '运维',
                'adjust'        => '是',
                'answer1'         => '除此之外，小米11新版系统修复了虚拟AB分区异常重启后判断异常导致OTA启动失败的问题；修复了低概率闪屏问题。',
                'answer2'   => '除此之外，小米11新版系统修复了虚拟AB分区异常重启后判断异常导致OTA启动失败的问题；修复了低概率闪屏问题。',
                'answer3'    => '除此之外，小米11新版系统修复了虚拟AB分区异常重启后判断异常导致OTA启动失败的问题；修复了低概率闪屏问题。',
                'update_time'    => date('Y-m-d H:i:s')]
        ]
    ];

    echo json_encode($array);

